# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: domain-theme-router
spec:
  enabled: true
  requires: ">=2.24.0"
  author:
    name: Lywq
    website: https://blog.muyin.site
  logo: logo.svg
  homepage: https://blog.muyin.site
  repo: https://github.com/liuyiwuqing/plugin-domain-theme-router
  issues: https://github.com/liuyiwuqing/plugin-domain-theme-router/issues
  displayName: "域名主题路由"
  description: "一套内容，无限可能 —— 让你的 Halo 站点在不同域名下展现不同主题的风采"
  settingName: domain-theme-router-settings
  configMapName: domain-theme-router-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/liuyiwuqing/plugin-domain-theme-router/blob/main/LICENSE"
